// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

public interface ChargeIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.packtpub.v1.ChargeId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique charge ID from a charge creation request
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * unique charge ID from a charge creation request
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
