// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

/**
 * Protobuf type {@code com.packtpub.v1.CreateSourceReq}
 */
public final class CreateSourceReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.packtpub.v1.CreateSourceReq)
    CreateSourceReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateSourceReq.newBuilder() to construct.
  private CreateSourceReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateSourceReq() {
    type_ = "";
    currency_ = "";
    statementDescriptor_ = "";
    flow_ = 0;
    usage_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateSourceReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateSourceReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 16: {

            amount_ = input.readUInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 34: {
            com.packt.modern.api.grpc.v1.Owner.Builder subBuilder = null;
            if (owner_ != null) {
              subBuilder = owner_.toBuilder();
            }
            owner_ = input.readMessage(com.packt.modern.api.grpc.v1.Owner.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(owner_);
              owner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            statementDescriptor_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            flow_ = rawValue;
            break;
          }
          case 58: {
            com.packt.modern.api.grpc.v1.Receiver.Builder subBuilder = null;
            if (receiver_ != null) {
              subBuilder = receiver_.toBuilder();
            }
            receiver_ = input.readMessage(com.packt.modern.api.grpc.v1.Receiver.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(receiver_);
              receiver_ = subBuilder.buildPartial();
            }

            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            usage_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.packt.modern.api.grpc.v1.CreateSourceReq.class, com.packt.modern.api.grpc.v1.CreateSourceReq.Builder.class);
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.packtpub.v1.CreateSourceReq.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.packtpub.v1.Source source = 1;</code>
     * @return Whether the source field is set.
     */
    boolean hasSource();
    /**
     * <code>.com.packtpub.v1.Source source = 1;</code>
     * @return The source.
     */
    com.packt.modern.api.grpc.v1.Source getSource();
    /**
     * <code>.com.packtpub.v1.Source source = 1;</code>
     */
    com.packt.modern.api.grpc.v1.SourceOrBuilder getSourceOrBuilder();
  }
  /**
   * Protobuf type {@code com.packtpub.v1.CreateSourceReq.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.packtpub.v1.CreateSourceReq.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.packt.modern.api.grpc.v1.Source.Builder subBuilder = null;
              if (source_ != null) {
                subBuilder = source_.toBuilder();
              }
              source_ = input.readMessage(com.packt.modern.api.grpc.v1.Source.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(source_);
                source_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.modern.api.grpc.v1.CreateSourceReq.Response.class, com.packt.modern.api.grpc.v1.CreateSourceReq.Response.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private com.packt.modern.api.grpc.v1.Source source_;
    /**
     * <code>.com.packtpub.v1.Source source = 1;</code>
     * @return Whether the source field is set.
     */
    @java.lang.Override
    public boolean hasSource() {
      return source_ != null;
    }
    /**
     * <code>.com.packtpub.v1.Source source = 1;</code>
     * @return The source.
     */
    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Source getSource() {
      return source_ == null ? com.packt.modern.api.grpc.v1.Source.getDefaultInstance() : source_;
    }
    /**
     * <code>.com.packtpub.v1.Source source = 1;</code>
     */
    @java.lang.Override
    public com.packt.modern.api.grpc.v1.SourceOrBuilder getSourceOrBuilder() {
      return getSource();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (source_ != null) {
        output.writeMessage(1, getSource());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (source_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSource());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.packt.modern.api.grpc.v1.CreateSourceReq.Response)) {
        return super.equals(obj);
      }
      com.packt.modern.api.grpc.v1.CreateSourceReq.Response other = (com.packt.modern.api.grpc.v1.CreateSourceReq.Response) obj;

      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (!getSource()
            .equals(other.getSource())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.packt.modern.api.grpc.v1.CreateSourceReq.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packtpub.v1.CreateSourceReq.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.packtpub.v1.CreateSourceReq.Response)
        com.packt.modern.api.grpc.v1.CreateSourceReq.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.modern.api.grpc.v1.CreateSourceReq.Response.class, com.packt.modern.api.grpc.v1.CreateSourceReq.Response.Builder.class);
      }

      // Construct using com.packt.modern.api.grpc.v1.CreateSourceReq.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (sourceBuilder_ == null) {
          source_ = null;
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_Response_descriptor;
      }

      @java.lang.Override
      public com.packt.modern.api.grpc.v1.CreateSourceReq.Response getDefaultInstanceForType() {
        return com.packt.modern.api.grpc.v1.CreateSourceReq.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.packt.modern.api.grpc.v1.CreateSourceReq.Response build() {
        com.packt.modern.api.grpc.v1.CreateSourceReq.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.packt.modern.api.grpc.v1.CreateSourceReq.Response buildPartial() {
        com.packt.modern.api.grpc.v1.CreateSourceReq.Response result = new com.packt.modern.api.grpc.v1.CreateSourceReq.Response(this);
        if (sourceBuilder_ == null) {
          result.source_ = source_;
        } else {
          result.source_ = sourceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.modern.api.grpc.v1.CreateSourceReq.Response) {
          return mergeFrom((com.packt.modern.api.grpc.v1.CreateSourceReq.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.modern.api.grpc.v1.CreateSourceReq.Response other) {
        if (other == com.packt.modern.api.grpc.v1.CreateSourceReq.Response.getDefaultInstance()) return this;
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.modern.api.grpc.v1.CreateSourceReq.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.modern.api.grpc.v1.CreateSourceReq.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.packt.modern.api.grpc.v1.Source source_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.packt.modern.api.grpc.v1.Source, com.packt.modern.api.grpc.v1.Source.Builder, com.packt.modern.api.grpc.v1.SourceOrBuilder> sourceBuilder_;
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       * @return Whether the source field is set.
       */
      public boolean hasSource() {
        return sourceBuilder_ != null || source_ != null;
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       * @return The source.
       */
      public com.packt.modern.api.grpc.v1.Source getSource() {
        if (sourceBuilder_ == null) {
          return source_ == null ? com.packt.modern.api.grpc.v1.Source.getDefaultInstance() : source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      public Builder setSource(com.packt.modern.api.grpc.v1.Source value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
          onChanged();
        } else {
          sourceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      public Builder setSource(
          com.packt.modern.api.grpc.v1.Source.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
          onChanged();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      public Builder mergeSource(com.packt.modern.api.grpc.v1.Source value) {
        if (sourceBuilder_ == null) {
          if (source_ != null) {
            source_ =
              com.packt.modern.api.grpc.v1.Source.newBuilder(source_).mergeFrom(value).buildPartial();
          } else {
            source_ = value;
          }
          onChanged();
        } else {
          sourceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = null;
          onChanged();
        } else {
          source_ = null;
          sourceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      public com.packt.modern.api.grpc.v1.Source.Builder getSourceBuilder() {
        
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      public com.packt.modern.api.grpc.v1.SourceOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_ == null ?
              com.packt.modern.api.grpc.v1.Source.getDefaultInstance() : source_;
        }
      }
      /**
       * <code>.com.packtpub.v1.Source source = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.packt.modern.api.grpc.v1.Source, com.packt.modern.api.grpc.v1.Source.Builder, com.packt.modern.api.grpc.v1.SourceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.packt.modern.api.grpc.v1.Source, com.packt.modern.api.grpc.v1.Source.Builder, com.packt.modern.api.grpc.v1.SourceOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.packtpub.v1.CreateSourceReq.Response)
    }

    // @@protoc_insertion_point(class_scope:com.packtpub.v1.CreateSourceReq.Response)
    private static final com.packt.modern.api.grpc.v1.CreateSourceReq.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.packt.modern.api.grpc.v1.CreateSourceReq.Response();
    }

    public static com.packt.modern.api.grpc.v1.CreateSourceReq.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateSourceReq.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   * The type of the source to create. Required unless customer and original_source are specified
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The type of the source to create. Required unless customer and original_source are specified
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private int amount_;
  /**
   * <pre>
   * Optional. Amount associated with the source. This is the amount for which the source will be
   * chargeable once ready. Required for single_use sources. Not supported for receiver type
   * sources, where charge amount may not be specified until funds land.
   * </pre>
   *
   * <code>uint32 amount = 2;</code>
   * @return The amount.
   */
  @java.lang.Override
  public int getAmount() {
    return amount_;
  }

  public static final int CURRENCY_FIELD_NUMBER = 3;
  private volatile java.lang.Object currency_;
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string currency = 3;</code>
   * @return The currency.
   */
  @java.lang.Override
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string currency = 3;</code>
   * @return The bytes for currency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_FIELD_NUMBER = 4;
  private com.packt.modern.api.grpc.v1.Owner owner_;
  /**
   * <pre>
   * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
   * </pre>
   *
   * <code>.com.packtpub.v1.Owner owner = 4;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return owner_ != null;
  }
  /**
   * <pre>
   * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
   * </pre>
   *
   * <code>.com.packtpub.v1.Owner owner = 4;</code>
   * @return The owner.
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.Owner getOwner() {
    return owner_ == null ? com.packt.modern.api.grpc.v1.Owner.getDefaultInstance() : owner_;
  }
  /**
   * <pre>
   * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
   * </pre>
   *
   * <code>.com.packtpub.v1.Owner owner = 4;</code>
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.OwnerOrBuilder getOwnerOrBuilder() {
    return getOwner();
  }

  public static final int STATEMENTDESCRIPTOR_FIELD_NUMBER = 5;
  private volatile java.lang.Object statementDescriptor_;
  /**
   * <pre>
   * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
   * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
   * you may want to specify a statementDescriptor of RunClub 5K race ticket.
   * While many payment types will display this information, some may not display it at all.
   * </pre>
   *
   * <code>string statementDescriptor = 5;</code>
   * @return The statementDescriptor.
   */
  @java.lang.Override
  public java.lang.String getStatementDescriptor() {
    java.lang.Object ref = statementDescriptor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statementDescriptor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
   * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
   * you may want to specify a statementDescriptor of RunClub 5K race ticket.
   * While many payment types will display this information, some may not display it at all.
   * </pre>
   *
   * <code>string statementDescriptor = 5;</code>
   * @return The bytes for statementDescriptor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatementDescriptorBytes() {
    java.lang.Object ref = statementDescriptor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statementDescriptor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOW_FIELD_NUMBER = 6;
  private int flow_;
  /**
   * <pre>
   * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
   * </pre>
   *
   * <code>.com.packtpub.v1.Flow flow = 6;</code>
   * @return The enum numeric value on the wire for flow.
   */
  @java.lang.Override public int getFlowValue() {
    return flow_;
  }
  /**
   * <pre>
   * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
   * </pre>
   *
   * <code>.com.packtpub.v1.Flow flow = 6;</code>
   * @return The flow.
   */
  @java.lang.Override public com.packt.modern.api.grpc.v1.Flow getFlow() {
    @SuppressWarnings("deprecation")
    com.packt.modern.api.grpc.v1.Flow result = com.packt.modern.api.grpc.v1.Flow.valueOf(flow_);
    return result == null ? com.packt.modern.api.grpc.v1.Flow.UNRECOGNIZED : result;
  }

  public static final int RECEIVER_FIELD_NUMBER = 7;
  private com.packt.modern.api.grpc.v1.Receiver receiver_;
  /**
   * <pre>
   * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
   * @return Whether the receiver field is set.
   */
  @java.lang.Override
  public boolean hasReceiver() {
    return receiver_ != null;
  }
  /**
   * <pre>
   * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
   * @return The receiver.
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.Receiver getReceiver() {
    return receiver_ == null ? com.packt.modern.api.grpc.v1.Receiver.getDefaultInstance() : receiver_;
  }
  /**
   * <pre>
   * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.ReceiverOrBuilder getReceiverOrBuilder() {
    return getReceiver();
  }

  public static final int USAGE_FIELD_NUMBER = 8;
  private int usage_;
  /**
   * <pre>
   * Optional. Either reusable or single_use. Whether this source should be reusable or not.
   * Some source types may or may not be reusable by construction, while others may leave the option
   * at creation. If an incompatible value is passed, an error will be returned.
   * </pre>
   *
   * <code>.com.packtpub.v1.Usage usage = 8;</code>
   * @return The enum numeric value on the wire for usage.
   */
  @java.lang.Override public int getUsageValue() {
    return usage_;
  }
  /**
   * <pre>
   * Optional. Either reusable or single_use. Whether this source should be reusable or not.
   * Some source types may or may not be reusable by construction, while others may leave the option
   * at creation. If an incompatible value is passed, an error will be returned.
   * </pre>
   *
   * <code>.com.packtpub.v1.Usage usage = 8;</code>
   * @return The usage.
   */
  @java.lang.Override public com.packt.modern.api.grpc.v1.Usage getUsage() {
    @SuppressWarnings("deprecation")
    com.packt.modern.api.grpc.v1.Usage result = com.packt.modern.api.grpc.v1.Usage.valueOf(usage_);
    return result == null ? com.packt.modern.api.grpc.v1.Usage.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (amount_ != 0) {
      output.writeUInt32(2, amount_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, currency_);
    }
    if (owner_ != null) {
      output.writeMessage(4, getOwner());
    }
    if (!getStatementDescriptorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, statementDescriptor_);
    }
    if (flow_ != com.packt.modern.api.grpc.v1.Flow.REDIRECT.getNumber()) {
      output.writeEnum(6, flow_);
    }
    if (receiver_ != null) {
      output.writeMessage(7, getReceiver());
    }
    if (usage_ != com.packt.modern.api.grpc.v1.Usage.REUSABLE.getNumber()) {
      output.writeEnum(8, usage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (amount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, amount_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, currency_);
    }
    if (owner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOwner());
    }
    if (!getStatementDescriptorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, statementDescriptor_);
    }
    if (flow_ != com.packt.modern.api.grpc.v1.Flow.REDIRECT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, flow_);
    }
    if (receiver_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getReceiver());
    }
    if (usage_ != com.packt.modern.api.grpc.v1.Usage.REUSABLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, usage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.packt.modern.api.grpc.v1.CreateSourceReq)) {
      return super.equals(obj);
    }
    com.packt.modern.api.grpc.v1.CreateSourceReq other = (com.packt.modern.api.grpc.v1.CreateSourceReq) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!getCurrency()
        .equals(other.getCurrency())) return false;
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (!getStatementDescriptor()
        .equals(other.getStatementDescriptor())) return false;
    if (flow_ != other.flow_) return false;
    if (hasReceiver() != other.hasReceiver()) return false;
    if (hasReceiver()) {
      if (!getReceiver()
          .equals(other.getReceiver())) return false;
    }
    if (usage_ != other.usage_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    hash = (37 * hash) + STATEMENTDESCRIPTOR_FIELD_NUMBER;
    hash = (53 * hash) + getStatementDescriptor().hashCode();
    hash = (37 * hash) + FLOW_FIELD_NUMBER;
    hash = (53 * hash) + flow_;
    if (hasReceiver()) {
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
    }
    hash = (37 * hash) + USAGE_FIELD_NUMBER;
    hash = (53 * hash) + usage_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.CreateSourceReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.packt.modern.api.grpc.v1.CreateSourceReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.packtpub.v1.CreateSourceReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.packtpub.v1.CreateSourceReq)
      com.packt.modern.api.grpc.v1.CreateSourceReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.modern.api.grpc.v1.CreateSourceReq.class, com.packt.modern.api.grpc.v1.CreateSourceReq.Builder.class);
    }

    // Construct using com.packt.modern.api.grpc.v1.CreateSourceReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      amount_ = 0;

      currency_ = "";

      if (ownerBuilder_ == null) {
        owner_ = null;
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }
      statementDescriptor_ = "";

      flow_ = 0;

      if (receiverBuilder_ == null) {
        receiver_ = null;
      } else {
        receiver_ = null;
        receiverBuilder_ = null;
      }
      usage_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateSourceReq_descriptor;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateSourceReq getDefaultInstanceForType() {
      return com.packt.modern.api.grpc.v1.CreateSourceReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateSourceReq build() {
      com.packt.modern.api.grpc.v1.CreateSourceReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateSourceReq buildPartial() {
      com.packt.modern.api.grpc.v1.CreateSourceReq result = new com.packt.modern.api.grpc.v1.CreateSourceReq(this);
      result.type_ = type_;
      result.amount_ = amount_;
      result.currency_ = currency_;
      if (ownerBuilder_ == null) {
        result.owner_ = owner_;
      } else {
        result.owner_ = ownerBuilder_.build();
      }
      result.statementDescriptor_ = statementDescriptor_;
      result.flow_ = flow_;
      if (receiverBuilder_ == null) {
        result.receiver_ = receiver_;
      } else {
        result.receiver_ = receiverBuilder_.build();
      }
      result.usage_ = usage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.packt.modern.api.grpc.v1.CreateSourceReq) {
        return mergeFrom((com.packt.modern.api.grpc.v1.CreateSourceReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.packt.modern.api.grpc.v1.CreateSourceReq other) {
      if (other == com.packt.modern.api.grpc.v1.CreateSourceReq.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getAmount() != 0) {
        setAmount(other.getAmount());
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (!other.getStatementDescriptor().isEmpty()) {
        statementDescriptor_ = other.statementDescriptor_;
        onChanged();
      }
      if (other.flow_ != 0) {
        setFlowValue(other.getFlowValue());
      }
      if (other.hasReceiver()) {
        mergeReceiver(other.getReceiver());
      }
      if (other.usage_ != 0) {
        setUsageValue(other.getUsageValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.packt.modern.api.grpc.v1.CreateSourceReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.packt.modern.api.grpc.v1.CreateSourceReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * The type of the source to create. Required unless customer and original_source are specified
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The type of the source to create. Required unless customer and original_source are specified
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The type of the source to create. Required unless customer and original_source are specified
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the source to create. Required unless customer and original_source are specified
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the source to create. Required unless customer and original_source are specified
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int amount_ ;
    /**
     * <pre>
     * Optional. Amount associated with the source. This is the amount for which the source will be
     * chargeable once ready. Required for single_use sources. Not supported for receiver type
     * sources, where charge amount may not be specified until funds land.
     * </pre>
     *
     * <code>uint32 amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public int getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * Optional. Amount associated with the source. This is the amount for which the source will be
     * chargeable once ready. Required for single_use sources. Not supported for receiver type
     * sources, where charge amount may not be specified until funds land.
     * </pre>
     *
     * <code>uint32 amount = 2;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(int value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Amount associated with the source. This is the amount for which the source will be
     * chargeable once ready. Required for single_use sources. Not supported for receiver type
     * sources, where charge amount may not be specified until funds land.
     * </pre>
     *
     * <code>uint32 amount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string currency = 3;</code>
     * @return The currency.
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string currency = 3;</code>
     * @return The bytes for currency.
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string currency = 3;</code>
     * @param value The currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string currency = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string currency = 3;</code>
     * @param value The bytes for currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private com.packt.modern.api.grpc.v1.Owner owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Owner, com.packt.modern.api.grpc.v1.Owner.Builder, com.packt.modern.api.grpc.v1.OwnerOrBuilder> ownerBuilder_;
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ownerBuilder_ != null || owner_ != null;
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     * @return The owner.
     */
    public com.packt.modern.api.grpc.v1.Owner getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? com.packt.modern.api.grpc.v1.Owner.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    public Builder setOwner(com.packt.modern.api.grpc.v1.Owner value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
        onChanged();
      } else {
        ownerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    public Builder setOwner(
        com.packt.modern.api.grpc.v1.Owner.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
        onChanged();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    public Builder mergeOwner(com.packt.modern.api.grpc.v1.Owner value) {
      if (ownerBuilder_ == null) {
        if (owner_ != null) {
          owner_ =
            com.packt.modern.api.grpc.v1.Owner.newBuilder(owner_).mergeFrom(value).buildPartial();
        } else {
          owner_ = value;
        }
        onChanged();
      } else {
        ownerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    public Builder clearOwner() {
      if (ownerBuilder_ == null) {
        owner_ = null;
        onChanged();
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    public com.packt.modern.api.grpc.v1.Owner.Builder getOwnerBuilder() {
      
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    public com.packt.modern.api.grpc.v1.OwnerOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            com.packt.modern.api.grpc.v1.Owner.getDefaultInstance() : owner_;
      }
    }
    /**
     * <pre>
     * Optional. Info about the owner of the payment instrument that may be used or required by particular source types.
     * </pre>
     *
     * <code>.com.packtpub.v1.Owner owner = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Owner, com.packt.modern.api.grpc.v1.Owner.Builder, com.packt.modern.api.grpc.v1.OwnerOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.packt.modern.api.grpc.v1.Owner, com.packt.modern.api.grpc.v1.Owner.Builder, com.packt.modern.api.grpc.v1.OwnerOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private java.lang.Object statementDescriptor_ = "";
    /**
     * <pre>
     * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
     * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
     * you may want to specify a statementDescriptor of RunClub 5K race ticket.
     * While many payment types will display this information, some may not display it at all.
     * </pre>
     *
     * <code>string statementDescriptor = 5;</code>
     * @return The statementDescriptor.
     */
    public java.lang.String getStatementDescriptor() {
      java.lang.Object ref = statementDescriptor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statementDescriptor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
     * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
     * you may want to specify a statementDescriptor of RunClub 5K race ticket.
     * While many payment types will display this information, some may not display it at all.
     * </pre>
     *
     * <code>string statementDescriptor = 5;</code>
     * @return The bytes for statementDescriptor.
     */
    public com.google.protobuf.ByteString
        getStatementDescriptorBytes() {
      java.lang.Object ref = statementDescriptor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statementDescriptor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
     * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
     * you may want to specify a statementDescriptor of RunClub 5K race ticket.
     * While many payment types will display this information, some may not display it at all.
     * </pre>
     *
     * <code>string statementDescriptor = 5;</code>
     * @param value The statementDescriptor to set.
     * @return This builder for chaining.
     */
    public Builder setStatementDescriptor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      statementDescriptor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
     * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
     * you may want to specify a statementDescriptor of RunClub 5K race ticket.
     * While many payment types will display this information, some may not display it at all.
     * </pre>
     *
     * <code>string statementDescriptor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatementDescriptor() {
      
      statementDescriptor_ = getDefaultInstance().getStatementDescriptor();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Extra information about a source. This will appear on your customer’s statement every time you charge the source.
     * As an example, if your website is RunClub and the item you’re charging for is a race ticket,
     * you may want to specify a statementDescriptor of RunClub 5K race ticket.
     * While many payment types will display this information, some may not display it at all.
     * </pre>
     *
     * <code>string statementDescriptor = 5;</code>
     * @param value The bytes for statementDescriptor to set.
     * @return This builder for chaining.
     */
    public Builder setStatementDescriptorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      statementDescriptor_ = value;
      onChanged();
      return this;
    }

    private int flow_ = 0;
    /**
     * <pre>
     * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
     * </pre>
     *
     * <code>.com.packtpub.v1.Flow flow = 6;</code>
     * @return The enum numeric value on the wire for flow.
     */
    @java.lang.Override public int getFlowValue() {
      return flow_;
    }
    /**
     * <pre>
     * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
     * </pre>
     *
     * <code>.com.packtpub.v1.Flow flow = 6;</code>
     * @param value The enum numeric value on the wire for flow to set.
     * @return This builder for chaining.
     */
    public Builder setFlowValue(int value) {
      
      flow_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
     * </pre>
     *
     * <code>.com.packtpub.v1.Flow flow = 6;</code>
     * @return The flow.
     */
    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Flow getFlow() {
      @SuppressWarnings("deprecation")
      com.packt.modern.api.grpc.v1.Flow result = com.packt.modern.api.grpc.v1.Flow.valueOf(flow_);
      return result == null ? com.packt.modern.api.grpc.v1.Flow.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
     * </pre>
     *
     * <code>.com.packtpub.v1.Flow flow = 6;</code>
     * @param value The flow to set.
     * @return This builder for chaining.
     */
    public Builder setFlow(com.packt.modern.api.grpc.v1.Flow value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      flow_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The authentication flow of the source. flow is one of redirect, receiver, codeVerification, none.
     * </pre>
     *
     * <code>.com.packtpub.v1.Flow flow = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlow() {
      
      flow_ = 0;
      onChanged();
      return this;
    }

    private com.packt.modern.api.grpc.v1.Receiver receiver_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Receiver, com.packt.modern.api.grpc.v1.Receiver.Builder, com.packt.modern.api.grpc.v1.ReceiverOrBuilder> receiverBuilder_;
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     * @return Whether the receiver field is set.
     */
    public boolean hasReceiver() {
      return receiverBuilder_ != null || receiver_ != null;
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     * @return The receiver.
     */
    public com.packt.modern.api.grpc.v1.Receiver getReceiver() {
      if (receiverBuilder_ == null) {
        return receiver_ == null ? com.packt.modern.api.grpc.v1.Receiver.getDefaultInstance() : receiver_;
      } else {
        return receiverBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    public Builder setReceiver(com.packt.modern.api.grpc.v1.Receiver value) {
      if (receiverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        receiver_ = value;
        onChanged();
      } else {
        receiverBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    public Builder setReceiver(
        com.packt.modern.api.grpc.v1.Receiver.Builder builderForValue) {
      if (receiverBuilder_ == null) {
        receiver_ = builderForValue.build();
        onChanged();
      } else {
        receiverBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    public Builder mergeReceiver(com.packt.modern.api.grpc.v1.Receiver value) {
      if (receiverBuilder_ == null) {
        if (receiver_ != null) {
          receiver_ =
            com.packt.modern.api.grpc.v1.Receiver.newBuilder(receiver_).mergeFrom(value).buildPartial();
        } else {
          receiver_ = value;
        }
        onChanged();
      } else {
        receiverBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    public Builder clearReceiver() {
      if (receiverBuilder_ == null) {
        receiver_ = null;
        onChanged();
      } else {
        receiver_ = null;
        receiverBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    public com.packt.modern.api.grpc.v1.Receiver.Builder getReceiverBuilder() {
      
      onChanged();
      return getReceiverFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    public com.packt.modern.api.grpc.v1.ReceiverOrBuilder getReceiverOrBuilder() {
      if (receiverBuilder_ != null) {
        return receiverBuilder_.getMessageOrBuilder();
      } else {
        return receiver_ == null ?
            com.packt.modern.api.grpc.v1.Receiver.getDefaultInstance() : receiver_;
      }
    }
    /**
     * <pre>
     * Optional. Information related to the receiver flow. Present if the source is a receiver (flow is receiver).
     * </pre>
     *
     * <code>.com.packtpub.v1.Receiver receiver = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Receiver, com.packt.modern.api.grpc.v1.Receiver.Builder, com.packt.modern.api.grpc.v1.ReceiverOrBuilder> 
        getReceiverFieldBuilder() {
      if (receiverBuilder_ == null) {
        receiverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.packt.modern.api.grpc.v1.Receiver, com.packt.modern.api.grpc.v1.Receiver.Builder, com.packt.modern.api.grpc.v1.ReceiverOrBuilder>(
                getReceiver(),
                getParentForChildren(),
                isClean());
        receiver_ = null;
      }
      return receiverBuilder_;
    }

    private int usage_ = 0;
    /**
     * <pre>
     * Optional. Either reusable or single_use. Whether this source should be reusable or not.
     * Some source types may or may not be reusable by construction, while others may leave the option
     * at creation. If an incompatible value is passed, an error will be returned.
     * </pre>
     *
     * <code>.com.packtpub.v1.Usage usage = 8;</code>
     * @return The enum numeric value on the wire for usage.
     */
    @java.lang.Override public int getUsageValue() {
      return usage_;
    }
    /**
     * <pre>
     * Optional. Either reusable or single_use. Whether this source should be reusable or not.
     * Some source types may or may not be reusable by construction, while others may leave the option
     * at creation. If an incompatible value is passed, an error will be returned.
     * </pre>
     *
     * <code>.com.packtpub.v1.Usage usage = 8;</code>
     * @param value The enum numeric value on the wire for usage to set.
     * @return This builder for chaining.
     */
    public Builder setUsageValue(int value) {
      
      usage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Either reusable or single_use. Whether this source should be reusable or not.
     * Some source types may or may not be reusable by construction, while others may leave the option
     * at creation. If an incompatible value is passed, an error will be returned.
     * </pre>
     *
     * <code>.com.packtpub.v1.Usage usage = 8;</code>
     * @return The usage.
     */
    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Usage getUsage() {
      @SuppressWarnings("deprecation")
      com.packt.modern.api.grpc.v1.Usage result = com.packt.modern.api.grpc.v1.Usage.valueOf(usage_);
      return result == null ? com.packt.modern.api.grpc.v1.Usage.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Optional. Either reusable or single_use. Whether this source should be reusable or not.
     * Some source types may or may not be reusable by construction, while others may leave the option
     * at creation. If an incompatible value is passed, an error will be returned.
     * </pre>
     *
     * <code>.com.packtpub.v1.Usage usage = 8;</code>
     * @param value The usage to set.
     * @return This builder for chaining.
     */
    public Builder setUsage(com.packt.modern.api.grpc.v1.Usage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      usage_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Either reusable or single_use. Whether this source should be reusable or not.
     * Some source types may or may not be reusable by construction, while others may leave the option
     * at creation. If an incompatible value is passed, an error will be returned.
     * </pre>
     *
     * <code>.com.packtpub.v1.Usage usage = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsage() {
      
      usage_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.packtpub.v1.CreateSourceReq)
  }

  // @@protoc_insertion_point(class_scope:com.packtpub.v1.CreateSourceReq)
  private static final com.packt.modern.api.grpc.v1.CreateSourceReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.packt.modern.api.grpc.v1.CreateSourceReq();
  }

  public static com.packt.modern.api.grpc.v1.CreateSourceReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSourceReq>
      PARSER = new com.google.protobuf.AbstractParser<CreateSourceReq>() {
    @java.lang.Override
    public CreateSourceReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateSourceReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateSourceReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSourceReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.packt.modern.api.grpc.v1.CreateSourceReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

