// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

public interface ReceiverOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.packtpub.v1.Receiver)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The address of the receiver source. This is the value that should be communicated to the customer to send their funds to.
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * The address of the receiver source. This is the value that should be communicated to the customer to send their funds to.
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * The total amount that was moved to your balance. This is almost always equal to the amount charged. In rare cases when customers deposit excess funds and we are unable to refund those, those funds get moved to your balance and show up in amountCharged as well. The amount charged is expressed in the source’s currency.
   * </pre>
   *
   * <code>uint32 amountCharged = 2;</code>
   * @return The amountCharged.
   */
  int getAmountCharged();

  /**
   * <pre>
   * The total amount received by the receiver source. amountReceived = amountReturned + amountCharged should be true for consumed sources unless customers deposit excess funds. The amount received is expressed in the source’s currency.
   * </pre>
   *
   * <code>uint32 amountReceived = 3;</code>
   * @return The amountReceived.
   */
  int getAmountReceived();

  /**
   * <pre>
   * The total amount that was returned to the customer. The amount returned is expressed in the source’s currency.
   * </pre>
   *
   * <code>uint32 amountReturned = 4;</code>
   * @return The amountReturned.
   */
  int getAmountReturned();

  /**
   * <pre>
   * Type of refund attribute method, one of email, manual, or none.
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver.RefundAttributesMethod refundAttributesMethod = 5;</code>
   * @return The enum numeric value on the wire for refundAttributesMethod.
   */
  int getRefundAttributesMethodValue();
  /**
   * <pre>
   * Type of refund attribute method, one of email, manual, or none.
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver.RefundAttributesMethod refundAttributesMethod = 5;</code>
   * @return The refundAttributesMethod.
   */
  com.packt.modern.api.grpc.v1.Receiver.RefundAttributesMethod getRefundAttributesMethod();

  /**
   * <pre>
   * Type of refund attribute status, one of missing, requested, or available.
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver.RefundAttributeStatus refundAttributesStatus = 6;</code>
   * @return The enum numeric value on the wire for refundAttributesStatus.
   */
  int getRefundAttributesStatusValue();
  /**
   * <pre>
   * Type of refund attribute status, one of missing, requested, or available.
   * </pre>
   *
   * <code>.com.packtpub.v1.Receiver.RefundAttributeStatus refundAttributesStatus = 6;</code>
   * @return The refundAttributesStatus.
   */
  com.packt.modern.api.grpc.v1.Receiver.RefundAttributeStatus getRefundAttributesStatus();
}
