// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

/**
 * Protobuf type {@code com.packtpub.v1.CreateChargeReq}
 */
public final class CreateChargeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.packtpub.v1.CreateChargeReq)
    CreateChargeReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateChargeReq.newBuilder() to construct.
  private CreateChargeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateChargeReq() {
    currency_ = "";
    customerId_ = "";
    description_ = "";
    receiptEmail_ = "";
    sourceId_ = "";
    statementDescriptor_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateChargeReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateChargeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            amount_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            customerId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            receiptEmail_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            statementDescriptor_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.packt.modern.api.grpc.v1.CreateChargeReq.class, com.packt.modern.api.grpc.v1.CreateChargeReq.Builder.class);
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.packtpub.v1.CreateChargeReq.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.packtpub.v1.Charge charge = 1;</code>
     * @return Whether the charge field is set.
     */
    boolean hasCharge();
    /**
     * <code>.com.packtpub.v1.Charge charge = 1;</code>
     * @return The charge.
     */
    com.packt.modern.api.grpc.v1.Charge getCharge();
    /**
     * <code>.com.packtpub.v1.Charge charge = 1;</code>
     */
    com.packt.modern.api.grpc.v1.ChargeOrBuilder getChargeOrBuilder();
  }
  /**
   * Protobuf type {@code com.packtpub.v1.CreateChargeReq.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.packtpub.v1.CreateChargeReq.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.packt.modern.api.grpc.v1.Charge.Builder subBuilder = null;
              if (charge_ != null) {
                subBuilder = charge_.toBuilder();
              }
              charge_ = input.readMessage(com.packt.modern.api.grpc.v1.Charge.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(charge_);
                charge_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.modern.api.grpc.v1.CreateChargeReq.Response.class, com.packt.modern.api.grpc.v1.CreateChargeReq.Response.Builder.class);
    }

    public static final int CHARGE_FIELD_NUMBER = 1;
    private com.packt.modern.api.grpc.v1.Charge charge_;
    /**
     * <code>.com.packtpub.v1.Charge charge = 1;</code>
     * @return Whether the charge field is set.
     */
    @java.lang.Override
    public boolean hasCharge() {
      return charge_ != null;
    }
    /**
     * <code>.com.packtpub.v1.Charge charge = 1;</code>
     * @return The charge.
     */
    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Charge getCharge() {
      return charge_ == null ? com.packt.modern.api.grpc.v1.Charge.getDefaultInstance() : charge_;
    }
    /**
     * <code>.com.packtpub.v1.Charge charge = 1;</code>
     */
    @java.lang.Override
    public com.packt.modern.api.grpc.v1.ChargeOrBuilder getChargeOrBuilder() {
      return getCharge();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (charge_ != null) {
        output.writeMessage(1, getCharge());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (charge_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCharge());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.packt.modern.api.grpc.v1.CreateChargeReq.Response)) {
        return super.equals(obj);
      }
      com.packt.modern.api.grpc.v1.CreateChargeReq.Response other = (com.packt.modern.api.grpc.v1.CreateChargeReq.Response) obj;

      if (hasCharge() != other.hasCharge()) return false;
      if (hasCharge()) {
        if (!getCharge()
            .equals(other.getCharge())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCharge()) {
        hash = (37 * hash) + CHARGE_FIELD_NUMBER;
        hash = (53 * hash) + getCharge().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.packt.modern.api.grpc.v1.CreateChargeReq.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packtpub.v1.CreateChargeReq.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.packtpub.v1.CreateChargeReq.Response)
        com.packt.modern.api.grpc.v1.CreateChargeReq.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.modern.api.grpc.v1.CreateChargeReq.Response.class, com.packt.modern.api.grpc.v1.CreateChargeReq.Response.Builder.class);
      }

      // Construct using com.packt.modern.api.grpc.v1.CreateChargeReq.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (chargeBuilder_ == null) {
          charge_ = null;
        } else {
          charge_ = null;
          chargeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_Response_descriptor;
      }

      @java.lang.Override
      public com.packt.modern.api.grpc.v1.CreateChargeReq.Response getDefaultInstanceForType() {
        return com.packt.modern.api.grpc.v1.CreateChargeReq.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.packt.modern.api.grpc.v1.CreateChargeReq.Response build() {
        com.packt.modern.api.grpc.v1.CreateChargeReq.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.packt.modern.api.grpc.v1.CreateChargeReq.Response buildPartial() {
        com.packt.modern.api.grpc.v1.CreateChargeReq.Response result = new com.packt.modern.api.grpc.v1.CreateChargeReq.Response(this);
        if (chargeBuilder_ == null) {
          result.charge_ = charge_;
        } else {
          result.charge_ = chargeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.modern.api.grpc.v1.CreateChargeReq.Response) {
          return mergeFrom((com.packt.modern.api.grpc.v1.CreateChargeReq.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.modern.api.grpc.v1.CreateChargeReq.Response other) {
        if (other == com.packt.modern.api.grpc.v1.CreateChargeReq.Response.getDefaultInstance()) return this;
        if (other.hasCharge()) {
          mergeCharge(other.getCharge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.modern.api.grpc.v1.CreateChargeReq.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.modern.api.grpc.v1.CreateChargeReq.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.packt.modern.api.grpc.v1.Charge charge_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.packt.modern.api.grpc.v1.Charge, com.packt.modern.api.grpc.v1.Charge.Builder, com.packt.modern.api.grpc.v1.ChargeOrBuilder> chargeBuilder_;
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       * @return Whether the charge field is set.
       */
      public boolean hasCharge() {
        return chargeBuilder_ != null || charge_ != null;
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       * @return The charge.
       */
      public com.packt.modern.api.grpc.v1.Charge getCharge() {
        if (chargeBuilder_ == null) {
          return charge_ == null ? com.packt.modern.api.grpc.v1.Charge.getDefaultInstance() : charge_;
        } else {
          return chargeBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      public Builder setCharge(com.packt.modern.api.grpc.v1.Charge value) {
        if (chargeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          charge_ = value;
          onChanged();
        } else {
          chargeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      public Builder setCharge(
          com.packt.modern.api.grpc.v1.Charge.Builder builderForValue) {
        if (chargeBuilder_ == null) {
          charge_ = builderForValue.build();
          onChanged();
        } else {
          chargeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      public Builder mergeCharge(com.packt.modern.api.grpc.v1.Charge value) {
        if (chargeBuilder_ == null) {
          if (charge_ != null) {
            charge_ =
              com.packt.modern.api.grpc.v1.Charge.newBuilder(charge_).mergeFrom(value).buildPartial();
          } else {
            charge_ = value;
          }
          onChanged();
        } else {
          chargeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      public Builder clearCharge() {
        if (chargeBuilder_ == null) {
          charge_ = null;
          onChanged();
        } else {
          charge_ = null;
          chargeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      public com.packt.modern.api.grpc.v1.Charge.Builder getChargeBuilder() {
        
        onChanged();
        return getChargeFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      public com.packt.modern.api.grpc.v1.ChargeOrBuilder getChargeOrBuilder() {
        if (chargeBuilder_ != null) {
          return chargeBuilder_.getMessageOrBuilder();
        } else {
          return charge_ == null ?
              com.packt.modern.api.grpc.v1.Charge.getDefaultInstance() : charge_;
        }
      }
      /**
       * <code>.com.packtpub.v1.Charge charge = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.packt.modern.api.grpc.v1.Charge, com.packt.modern.api.grpc.v1.Charge.Builder, com.packt.modern.api.grpc.v1.ChargeOrBuilder> 
          getChargeFieldBuilder() {
        if (chargeBuilder_ == null) {
          chargeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.packt.modern.api.grpc.v1.Charge, com.packt.modern.api.grpc.v1.Charge.Builder, com.packt.modern.api.grpc.v1.ChargeOrBuilder>(
                  getCharge(),
                  getParentForChildren(),
                  isClean());
          charge_ = null;
        }
        return chargeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.packtpub.v1.CreateChargeReq.Response)
    }

    // @@protoc_insertion_point(class_scope:com.packtpub.v1.CreateChargeReq.Response)
    private static final com.packt.modern.api.grpc.v1.CreateChargeReq.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.packt.modern.api.grpc.v1.CreateChargeReq.Response();
    }

    public static com.packt.modern.api.grpc.v1.CreateChargeReq.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateChargeReq.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int AMOUNT_FIELD_NUMBER = 1;
  private int amount_;
  /**
   * <pre>
   *Required. Amount intended to be collected by this payment. A positive integer representing how
   * much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge
   * ¥100, a zero-decimal currency). The minimum amount is $0.50 US or equivalent in charge currency.
   *The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
   * </pre>
   *
   * <code>uint32 amount = 1;</code>
   * @return The amount.
   */
  @java.lang.Override
  public int getAmount() {
    return amount_;
  }

  public static final int CURRENCY_FIELD_NUMBER = 2;
  private volatile java.lang.Object currency_;
  /**
   * <pre>
   * Required. Three-letter ISO currency code, in lowercase.
   * </pre>
   *
   * <code>string currency = 2;</code>
   * @return The currency.
   */
  @java.lang.Override
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Three-letter ISO currency code, in lowercase.
   * </pre>
   *
   * <code>string currency = 2;</code>
   * @return The bytes for currency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMERID_FIELD_NUMBER = 3;
  private volatile java.lang.Object customerId_;
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string customerId = 3;</code>
   * @return The customerId.
   */
  @java.lang.Override
  public java.lang.String getCustomerId() {
    java.lang.Object ref = customerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string customerId = 3;</code>
   * @return The bytes for customerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerIdBytes() {
    java.lang.Object ref = customerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
   * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
   * receipts to your customers, your receipt emails will include the description of the charge(s)
   * that they are describing.
   * </pre>
   *
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
   * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
   * receipts to your customers, your receipt emails will include the description of the charge(s)
   * that they are describing.
   * </pre>
   *
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIPTEMAIL_FIELD_NUMBER = 5;
  private volatile java.lang.Object receiptEmail_;
  /**
   * <pre>
   * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
   * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
   * charge is for a Customer, the email address specified here will override the customer’s email
   * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
   * regardless of your email settings.
   * </pre>
   *
   * <code>string receiptEmail = 5;</code>
   * @return The receiptEmail.
   */
  @java.lang.Override
  public java.lang.String getReceiptEmail() {
    java.lang.Object ref = receiptEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiptEmail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
   * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
   * charge is for a Customer, the email address specified here will override the customer’s email
   * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
   * regardless of your email settings.
   * </pre>
   *
   * <code>string receiptEmail = 5;</code>
   * @return The bytes for receiptEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiptEmailBytes() {
    java.lang.Object ref = receiptEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiptEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEID_FIELD_NUMBER = 6;
  private volatile java.lang.Object sourceId_;
  /**
   * <pre>
   * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
   * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
   *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
   * </pre>
   *
   * <code>string sourceId = 6;</code>
   * @return The sourceId.
   */
  @java.lang.Override
  public java.lang.String getSourceId() {
    java.lang.Object ref = sourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
   * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
   *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
   * </pre>
   *
   * <code>string sourceId = 6;</code>
   * @return The bytes for sourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIdBytes() {
    java.lang.Object ref = sourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATEMENTDESCRIPTOR_FIELD_NUMBER = 7;
  private volatile java.lang.Object statementDescriptor_;
  /**
   * <pre>
   * Optional. For card charges
   * </pre>
   *
   * <code>string statementDescriptor = 7;</code>
   * @return The statementDescriptor.
   */
  @java.lang.Override
  public java.lang.String getStatementDescriptor() {
    java.lang.Object ref = statementDescriptor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statementDescriptor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. For card charges
   * </pre>
   *
   * <code>string statementDescriptor = 7;</code>
   * @return The bytes for statementDescriptor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatementDescriptorBytes() {
    java.lang.Object ref = statementDescriptor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statementDescriptor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (amount_ != 0) {
      output.writeUInt32(1, amount_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currency_);
    }
    if (!getCustomerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customerId_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (!getReceiptEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiptEmail_);
    }
    if (!getSourceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sourceId_);
    }
    if (!getStatementDescriptorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, statementDescriptor_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (amount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, amount_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currency_);
    }
    if (!getCustomerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, customerId_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (!getReceiptEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiptEmail_);
    }
    if (!getSourceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sourceId_);
    }
    if (!getStatementDescriptorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, statementDescriptor_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.packt.modern.api.grpc.v1.CreateChargeReq)) {
      return super.equals(obj);
    }
    com.packt.modern.api.grpc.v1.CreateChargeReq other = (com.packt.modern.api.grpc.v1.CreateChargeReq) obj;

    if (getAmount()
        != other.getAmount()) return false;
    if (!getCurrency()
        .equals(other.getCurrency())) return false;
    if (!getCustomerId()
        .equals(other.getCustomerId())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getReceiptEmail()
        .equals(other.getReceiptEmail())) return false;
    if (!getSourceId()
        .equals(other.getSourceId())) return false;
    if (!getStatementDescriptor()
        .equals(other.getStatementDescriptor())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerId().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + RECEIPTEMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getReceiptEmail().hashCode();
    hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceId().hashCode();
    hash = (37 * hash) + STATEMENTDESCRIPTOR_FIELD_NUMBER;
    hash = (53 * hash) + getStatementDescriptor().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.CreateChargeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.packt.modern.api.grpc.v1.CreateChargeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.packtpub.v1.CreateChargeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.packtpub.v1.CreateChargeReq)
      com.packt.modern.api.grpc.v1.CreateChargeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.modern.api.grpc.v1.CreateChargeReq.class, com.packt.modern.api.grpc.v1.CreateChargeReq.Builder.class);
    }

    // Construct using com.packt.modern.api.grpc.v1.CreateChargeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      amount_ = 0;

      currency_ = "";

      customerId_ = "";

      description_ = "";

      receiptEmail_ = "";

      sourceId_ = "";

      statementDescriptor_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_CreateChargeReq_descriptor;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateChargeReq getDefaultInstanceForType() {
      return com.packt.modern.api.grpc.v1.CreateChargeReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateChargeReq build() {
      com.packt.modern.api.grpc.v1.CreateChargeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.CreateChargeReq buildPartial() {
      com.packt.modern.api.grpc.v1.CreateChargeReq result = new com.packt.modern.api.grpc.v1.CreateChargeReq(this);
      result.amount_ = amount_;
      result.currency_ = currency_;
      result.customerId_ = customerId_;
      result.description_ = description_;
      result.receiptEmail_ = receiptEmail_;
      result.sourceId_ = sourceId_;
      result.statementDescriptor_ = statementDescriptor_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.packt.modern.api.grpc.v1.CreateChargeReq) {
        return mergeFrom((com.packt.modern.api.grpc.v1.CreateChargeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.packt.modern.api.grpc.v1.CreateChargeReq other) {
      if (other == com.packt.modern.api.grpc.v1.CreateChargeReq.getDefaultInstance()) return this;
      if (other.getAmount() != 0) {
        setAmount(other.getAmount());
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (!other.getCustomerId().isEmpty()) {
        customerId_ = other.customerId_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getReceiptEmail().isEmpty()) {
        receiptEmail_ = other.receiptEmail_;
        onChanged();
      }
      if (!other.getSourceId().isEmpty()) {
        sourceId_ = other.sourceId_;
        onChanged();
      }
      if (!other.getStatementDescriptor().isEmpty()) {
        statementDescriptor_ = other.statementDescriptor_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.packt.modern.api.grpc.v1.CreateChargeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.packt.modern.api.grpc.v1.CreateChargeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int amount_ ;
    /**
     * <pre>
     *Required. Amount intended to be collected by this payment. A positive integer representing how
     * much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge
     * ¥100, a zero-decimal currency). The minimum amount is $0.50 US or equivalent in charge currency.
     *The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
     * </pre>
     *
     * <code>uint32 amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public int getAmount() {
      return amount_;
    }
    /**
     * <pre>
     *Required. Amount intended to be collected by this payment. A positive integer representing how
     * much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge
     * ¥100, a zero-decimal currency). The minimum amount is $0.50 US or equivalent in charge currency.
     *The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
     * </pre>
     *
     * <code>uint32 amount = 1;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(int value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Required. Amount intended to be collected by this payment. A positive integer representing how
     * much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge
     * ¥100, a zero-decimal currency). The minimum amount is $0.50 US or equivalent in charge currency.
     *The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
     * </pre>
     *
     * <code>uint32 amount = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <pre>
     * Required. Three-letter ISO currency code, in lowercase.
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. Three-letter ISO currency code, in lowercase.
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Three-letter ISO currency code, in lowercase.
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @param value The currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Three-letter ISO currency code, in lowercase.
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Three-letter ISO currency code, in lowercase.
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @param value The bytes for currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerId_ = "";
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string customerId = 3;</code>
     * @return The customerId.
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string customerId = 3;</code>
     * @return The bytes for customerId.
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string customerId = 3;</code>
     * @param value The customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string customerId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerId() {
      
      customerId_ = getDefaultInstance().getCustomerId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional
     * </pre>
     *
     * <code>string customerId = 3;</code>
     * @param value The bytes for customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
     * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
     * receipts to your customers, your receipt emails will include the description of the charge(s)
     * that they are describing.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
     * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
     * receipts to your customers, your receipt emails will include the description of the charge(s)
     * that they are describing.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
     * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
     * receipts to your customers, your receipt emails will include the description of the charge(s)
     * that they are describing.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
     * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
     * receipts to your customers, your receipt emails will include the description of the charge(s)
     * that they are describing.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional. An arbitrary string which you can attach to a Charge object. It is displayed when
     * in the web interface alongside the charge. Note that if you use Stripe to send automatic email
     * receipts to your customers, your receipt emails will include the description of the charge(s)
     * that they are describing.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object receiptEmail_ = "";
    /**
     * <pre>
     * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
     * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
     * charge is for a Customer, the email address specified here will override the customer’s email
     * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
     * regardless of your email settings.
     * </pre>
     *
     * <code>string receiptEmail = 5;</code>
     * @return The receiptEmail.
     */
    public java.lang.String getReceiptEmail() {
      java.lang.Object ref = receiptEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiptEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
     * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
     * charge is for a Customer, the email address specified here will override the customer’s email
     * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
     * regardless of your email settings.
     * </pre>
     *
     * <code>string receiptEmail = 5;</code>
     * @return The bytes for receiptEmail.
     */
    public com.google.protobuf.ByteString
        getReceiptEmailBytes() {
      java.lang.Object ref = receiptEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiptEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
     * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
     * charge is for a Customer, the email address specified here will override the customer’s email
     * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
     * regardless of your email settings.
     * </pre>
     *
     * <code>string receiptEmail = 5;</code>
     * @param value The receiptEmail to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receiptEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
     * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
     * charge is for a Customer, the email address specified here will override the customer’s email
     * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
     * regardless of your email settings.
     * </pre>
     *
     * <code>string receiptEmail = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiptEmail() {
      
      receiptEmail_ = getDefaultInstance().getReceiptEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The email address to which this charge’s receipt will be sent. The receipt will not
     * be sent until the charge is paid, and no receipts will be sent for test mode charges. If this
     * charge is for a Customer, the email address specified here will override the customer’s email
     * address. If receiptEmail is specified for a charge in live mode, a receipt will be sent
     * regardless of your email settings.
     * </pre>
     *
     * <code>string receiptEmail = 5;</code>
     * @param value The bytes for receiptEmail to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receiptEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceId_ = "";
    /**
     * <pre>
     * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
     * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
     *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
     * </pre>
     *
     * <code>string sourceId = 6;</code>
     * @return The sourceId.
     */
    public java.lang.String getSourceId() {
      java.lang.Object ref = sourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
     * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
     *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
     * </pre>
     *
     * <code>string sourceId = 6;</code>
     * @return The bytes for sourceId.
     */
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
     * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
     *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
     * </pre>
     *
     * <code>string sourceId = 6;</code>
     * @param value The sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
     * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
     *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
     * </pre>
     *
     * <code>string sourceId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceId() {
      
      sourceId_ = getDefaultInstance().getSourceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. A payment source to be charged. This can be the ID of a card (i.e., credit or debit
     * card), a bank account, a source, a token, or a connected account. For certain sources—namely,
     *cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
     * </pre>
     *
     * <code>string sourceId = 6;</code>
     * @param value The bytes for sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object statementDescriptor_ = "";
    /**
     * <pre>
     * Optional. For card charges
     * </pre>
     *
     * <code>string statementDescriptor = 7;</code>
     * @return The statementDescriptor.
     */
    public java.lang.String getStatementDescriptor() {
      java.lang.Object ref = statementDescriptor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statementDescriptor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. For card charges
     * </pre>
     *
     * <code>string statementDescriptor = 7;</code>
     * @return The bytes for statementDescriptor.
     */
    public com.google.protobuf.ByteString
        getStatementDescriptorBytes() {
      java.lang.Object ref = statementDescriptor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statementDescriptor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. For card charges
     * </pre>
     *
     * <code>string statementDescriptor = 7;</code>
     * @param value The statementDescriptor to set.
     * @return This builder for chaining.
     */
    public Builder setStatementDescriptor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      statementDescriptor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. For card charges
     * </pre>
     *
     * <code>string statementDescriptor = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatementDescriptor() {
      
      statementDescriptor_ = getDefaultInstance().getStatementDescriptor();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. For card charges
     * </pre>
     *
     * <code>string statementDescriptor = 7;</code>
     * @param value The bytes for statementDescriptor to set.
     * @return This builder for chaining.
     */
    public Builder setStatementDescriptorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      statementDescriptor_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.packtpub.v1.CreateChargeReq)
  }

  // @@protoc_insertion_point(class_scope:com.packtpub.v1.CreateChargeReq)
  private static final com.packt.modern.api.grpc.v1.CreateChargeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.packt.modern.api.grpc.v1.CreateChargeReq();
  }

  public static com.packt.modern.api.grpc.v1.CreateChargeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateChargeReq>
      PARSER = new com.google.protobuf.AbstractParser<CreateChargeReq>() {
    @java.lang.Override
    public CreateChargeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateChargeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateChargeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateChargeReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.packt.modern.api.grpc.v1.CreateChargeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

