// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

public interface CustomerIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.packtpub.v1.CustomerId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique customer ID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * unique customer ID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
