// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

/**
 * Protobuf type {@code com.packtpub.v1.Owner}
 */
public final class Owner extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.packtpub.v1.Owner)
    OwnerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Owner.newBuilder() to construct.
  private Owner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Owner() {
    email_ = "";
    name_ = "";
    phone_ = "";
    verifiedEmail_ = "";
    verifiedName_ = "";
    verifiedPhone_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Owner();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Owner(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.packt.modern.api.grpc.v1.Address.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(com.packt.modern.api.grpc.v1.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            phone_ = s;
            break;
          }
          case 42: {
            com.packt.modern.api.grpc.v1.Address.Builder subBuilder = null;
            if (verifiedAddress_ != null) {
              subBuilder = verifiedAddress_.toBuilder();
            }
            verifiedAddress_ = input.readMessage(com.packt.modern.api.grpc.v1.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(verifiedAddress_);
              verifiedAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            verifiedEmail_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            verifiedName_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            verifiedPhone_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_Owner_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_Owner_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.packt.modern.api.grpc.v1.Owner.class, com.packt.modern.api.grpc.v1.Owner.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private com.packt.modern.api.grpc.v1.Address address_;
  /**
   * <pre>
   * Owner’s address.
   * </pre>
   *
   * <code>.com.packtpub.v1.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <pre>
   * Owner’s address.
   * </pre>
   *
   * <code>.com.packtpub.v1.Address address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.Address getAddress() {
    return address_ == null ? com.packt.modern.api.grpc.v1.Address.getDefaultInstance() : address_;
  }
  /**
   * <pre>
   * Owner’s address.
   * </pre>
   *
   * <code>.com.packtpub.v1.Address address = 1;</code>
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   * Owner’s email address.
   * </pre>
   *
   * <code>string email = 2;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Owner’s email address.
   * </pre>
   *
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Owner’s full name.
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Owner’s full name.
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 4;
  private volatile java.lang.Object phone_;
  /**
   * <pre>
   * Owner’s phone number (including extension).
   * </pre>
   *
   * <code>string phone = 4;</code>
   * @return The phone.
   */
  @java.lang.Override
  public java.lang.String getPhone() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Owner’s phone number (including extension).
   * </pre>
   *
   * <code>string phone = 4;</code>
   * @return The bytes for phone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFIEDADDRESS_FIELD_NUMBER = 5;
  private com.packt.modern.api.grpc.v1.Address verifiedAddress_;
  /**
   * <pre>
   * Verified values are verified or provided by the payment method directly
   * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
   * Verified owner’s address.
   * </pre>
   *
   * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
   * @return Whether the verifiedAddress field is set.
   */
  @java.lang.Override
  public boolean hasVerifiedAddress() {
    return verifiedAddress_ != null;
  }
  /**
   * <pre>
   * Verified values are verified or provided by the payment method directly
   * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
   * Verified owner’s address.
   * </pre>
   *
   * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
   * @return The verifiedAddress.
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.Address getVerifiedAddress() {
    return verifiedAddress_ == null ? com.packt.modern.api.grpc.v1.Address.getDefaultInstance() : verifiedAddress_;
  }
  /**
   * <pre>
   * Verified values are verified or provided by the payment method directly
   * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
   * Verified owner’s address.
   * </pre>
   *
   * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
   */
  @java.lang.Override
  public com.packt.modern.api.grpc.v1.AddressOrBuilder getVerifiedAddressOrBuilder() {
    return getVerifiedAddress();
  }

  public static final int VERIFIEDEMAIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object verifiedEmail_;
  /**
   * <pre>
   * Verified owner’s email address.
   * </pre>
   *
   * <code>string verifiedEmail = 6;</code>
   * @return The verifiedEmail.
   */
  @java.lang.Override
  public java.lang.String getVerifiedEmail() {
    java.lang.Object ref = verifiedEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifiedEmail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Verified owner’s email address.
   * </pre>
   *
   * <code>string verifiedEmail = 6;</code>
   * @return The bytes for verifiedEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVerifiedEmailBytes() {
    java.lang.Object ref = verifiedEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifiedEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFIEDNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object verifiedName_;
  /**
   * <pre>
   * Verified owner’s full name.
   * </pre>
   *
   * <code>string verifiedName = 7;</code>
   * @return The verifiedName.
   */
  @java.lang.Override
  public java.lang.String getVerifiedName() {
    java.lang.Object ref = verifiedName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifiedName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Verified owner’s full name.
   * </pre>
   *
   * <code>string verifiedName = 7;</code>
   * @return The bytes for verifiedName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVerifiedNameBytes() {
    java.lang.Object ref = verifiedName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifiedName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFIEDPHONE_FIELD_NUMBER = 8;
  private volatile java.lang.Object verifiedPhone_;
  /**
   * <pre>
   * Verified owner’s phone number
   * </pre>
   *
   * <code>string verifiedPhone = 8;</code>
   * @return The verifiedPhone.
   */
  @java.lang.Override
  public java.lang.String getVerifiedPhone() {
    java.lang.Object ref = verifiedPhone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifiedPhone_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Verified owner’s phone number
   * </pre>
   *
   * <code>string verifiedPhone = 8;</code>
   * @return The bytes for verifiedPhone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVerifiedPhoneBytes() {
    java.lang.Object ref = verifiedPhone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifiedPhone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (address_ != null) {
      output.writeMessage(1, getAddress());
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!getPhoneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phone_);
    }
    if (verifiedAddress_ != null) {
      output.writeMessage(5, getVerifiedAddress());
    }
    if (!getVerifiedEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, verifiedEmail_);
    }
    if (!getVerifiedNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, verifiedName_);
    }
    if (!getVerifiedPhoneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, verifiedPhone_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAddress());
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!getPhoneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phone_);
    }
    if (verifiedAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVerifiedAddress());
    }
    if (!getVerifiedEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, verifiedEmail_);
    }
    if (!getVerifiedNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, verifiedName_);
    }
    if (!getVerifiedPhoneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, verifiedPhone_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.packt.modern.api.grpc.v1.Owner)) {
      return super.equals(obj);
    }
    com.packt.modern.api.grpc.v1.Owner other = (com.packt.modern.api.grpc.v1.Owner) obj;

    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getPhone()
        .equals(other.getPhone())) return false;
    if (hasVerifiedAddress() != other.hasVerifiedAddress()) return false;
    if (hasVerifiedAddress()) {
      if (!getVerifiedAddress()
          .equals(other.getVerifiedAddress())) return false;
    }
    if (!getVerifiedEmail()
        .equals(other.getVerifiedEmail())) return false;
    if (!getVerifiedName()
        .equals(other.getVerifiedName())) return false;
    if (!getVerifiedPhone()
        .equals(other.getVerifiedPhone())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + getPhone().hashCode();
    if (hasVerifiedAddress()) {
      hash = (37 * hash) + VERIFIEDADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getVerifiedAddress().hashCode();
    }
    hash = (37 * hash) + VERIFIEDEMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getVerifiedEmail().hashCode();
    hash = (37 * hash) + VERIFIEDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getVerifiedName().hashCode();
    hash = (37 * hash) + VERIFIEDPHONE_FIELD_NUMBER;
    hash = (53 * hash) + getVerifiedPhone().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.packt.modern.api.grpc.v1.Owner parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.packt.modern.api.grpc.v1.Owner prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.packtpub.v1.Owner}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.packtpub.v1.Owner)
      com.packt.modern.api.grpc.v1.OwnerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_Owner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_Owner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.modern.api.grpc.v1.Owner.class, com.packt.modern.api.grpc.v1.Owner.Builder.class);
    }

    // Construct using com.packt.modern.api.grpc.v1.Owner.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      email_ = "";

      name_ = "";

      phone_ = "";

      if (verifiedAddressBuilder_ == null) {
        verifiedAddress_ = null;
      } else {
        verifiedAddress_ = null;
        verifiedAddressBuilder_ = null;
      }
      verifiedEmail_ = "";

      verifiedName_ = "";

      verifiedPhone_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.packt.modern.api.grpc.v1.PaymentGatewayService.internal_static_com_packtpub_v1_Owner_descriptor;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Owner getDefaultInstanceForType() {
      return com.packt.modern.api.grpc.v1.Owner.getDefaultInstance();
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Owner build() {
      com.packt.modern.api.grpc.v1.Owner result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.packt.modern.api.grpc.v1.Owner buildPartial() {
      com.packt.modern.api.grpc.v1.Owner result = new com.packt.modern.api.grpc.v1.Owner(this);
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.email_ = email_;
      result.name_ = name_;
      result.phone_ = phone_;
      if (verifiedAddressBuilder_ == null) {
        result.verifiedAddress_ = verifiedAddress_;
      } else {
        result.verifiedAddress_ = verifiedAddressBuilder_.build();
      }
      result.verifiedEmail_ = verifiedEmail_;
      result.verifiedName_ = verifiedName_;
      result.verifiedPhone_ = verifiedPhone_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.packt.modern.api.grpc.v1.Owner) {
        return mergeFrom((com.packt.modern.api.grpc.v1.Owner)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.packt.modern.api.grpc.v1.Owner other) {
      if (other == com.packt.modern.api.grpc.v1.Owner.getDefaultInstance()) return this;
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getPhone().isEmpty()) {
        phone_ = other.phone_;
        onChanged();
      }
      if (other.hasVerifiedAddress()) {
        mergeVerifiedAddress(other.getVerifiedAddress());
      }
      if (!other.getVerifiedEmail().isEmpty()) {
        verifiedEmail_ = other.verifiedEmail_;
        onChanged();
      }
      if (!other.getVerifiedName().isEmpty()) {
        verifiedName_ = other.verifiedName_;
        onChanged();
      }
      if (!other.getVerifiedPhone().isEmpty()) {
        verifiedPhone_ = other.verifiedPhone_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.packt.modern.api.grpc.v1.Owner parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.packt.modern.api.grpc.v1.Owner) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.packt.modern.api.grpc.v1.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Address, com.packt.modern.api.grpc.v1.Address.Builder, com.packt.modern.api.grpc.v1.AddressOrBuilder> addressBuilder_;
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     * @return The address.
     */
    public com.packt.modern.api.grpc.v1.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? com.packt.modern.api.grpc.v1.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    public Builder setAddress(com.packt.modern.api.grpc.v1.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    public Builder setAddress(
        com.packt.modern.api.grpc.v1.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    public Builder mergeAddress(com.packt.modern.api.grpc.v1.Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            com.packt.modern.api.grpc.v1.Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    public com.packt.modern.api.grpc.v1.Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    public com.packt.modern.api.grpc.v1.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            com.packt.modern.api.grpc.v1.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <pre>
     * Owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address address = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Address, com.packt.modern.api.grpc.v1.Address.Builder, com.packt.modern.api.grpc.v1.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.packt.modern.api.grpc.v1.Address, com.packt.modern.api.grpc.v1.Address.Builder, com.packt.modern.api.grpc.v1.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     * Owner’s email address.
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Owner’s email address.
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Owner’s email address.
     * </pre>
     *
     * <code>string email = 2;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Owner’s email address.
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Owner’s email address.
     * </pre>
     *
     * <code>string email = 2;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Owner’s full name.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Owner’s full name.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Owner’s full name.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Owner’s full name.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Owner’s full name.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone_ = "";
    /**
     * <pre>
     * Owner’s phone number (including extension).
     * </pre>
     *
     * <code>string phone = 4;</code>
     * @return The phone.
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Owner’s phone number (including extension).
     * </pre>
     *
     * <code>string phone = 4;</code>
     * @return The bytes for phone.
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Owner’s phone number (including extension).
     * </pre>
     *
     * <code>string phone = 4;</code>
     * @param value The phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phone_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Owner’s phone number (including extension).
     * </pre>
     *
     * <code>string phone = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone() {
      
      phone_ = getDefaultInstance().getPhone();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Owner’s phone number (including extension).
     * </pre>
     *
     * <code>string phone = 4;</code>
     * @param value The bytes for phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phone_ = value;
      onChanged();
      return this;
    }

    private com.packt.modern.api.grpc.v1.Address verifiedAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Address, com.packt.modern.api.grpc.v1.Address.Builder, com.packt.modern.api.grpc.v1.AddressOrBuilder> verifiedAddressBuilder_;
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     * @return Whether the verifiedAddress field is set.
     */
    public boolean hasVerifiedAddress() {
      return verifiedAddressBuilder_ != null || verifiedAddress_ != null;
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     * @return The verifiedAddress.
     */
    public com.packt.modern.api.grpc.v1.Address getVerifiedAddress() {
      if (verifiedAddressBuilder_ == null) {
        return verifiedAddress_ == null ? com.packt.modern.api.grpc.v1.Address.getDefaultInstance() : verifiedAddress_;
      } else {
        return verifiedAddressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    public Builder setVerifiedAddress(com.packt.modern.api.grpc.v1.Address value) {
      if (verifiedAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        verifiedAddress_ = value;
        onChanged();
      } else {
        verifiedAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    public Builder setVerifiedAddress(
        com.packt.modern.api.grpc.v1.Address.Builder builderForValue) {
      if (verifiedAddressBuilder_ == null) {
        verifiedAddress_ = builderForValue.build();
        onChanged();
      } else {
        verifiedAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    public Builder mergeVerifiedAddress(com.packt.modern.api.grpc.v1.Address value) {
      if (verifiedAddressBuilder_ == null) {
        if (verifiedAddress_ != null) {
          verifiedAddress_ =
            com.packt.modern.api.grpc.v1.Address.newBuilder(verifiedAddress_).mergeFrom(value).buildPartial();
        } else {
          verifiedAddress_ = value;
        }
        onChanged();
      } else {
        verifiedAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    public Builder clearVerifiedAddress() {
      if (verifiedAddressBuilder_ == null) {
        verifiedAddress_ = null;
        onChanged();
      } else {
        verifiedAddress_ = null;
        verifiedAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    public com.packt.modern.api.grpc.v1.Address.Builder getVerifiedAddressBuilder() {
      
      onChanged();
      return getVerifiedAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    public com.packt.modern.api.grpc.v1.AddressOrBuilder getVerifiedAddressOrBuilder() {
      if (verifiedAddressBuilder_ != null) {
        return verifiedAddressBuilder_.getMessageOrBuilder();
      } else {
        return verifiedAddress_ == null ?
            com.packt.modern.api.grpc.v1.Address.getDefaultInstance() : verifiedAddress_;
      }
    }
    /**
     * <pre>
     * Verified values are verified or provided by the payment method directly
     * (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
     * Verified owner’s address.
     * </pre>
     *
     * <code>.com.packtpub.v1.Address verifiedAddress = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.packt.modern.api.grpc.v1.Address, com.packt.modern.api.grpc.v1.Address.Builder, com.packt.modern.api.grpc.v1.AddressOrBuilder> 
        getVerifiedAddressFieldBuilder() {
      if (verifiedAddressBuilder_ == null) {
        verifiedAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.packt.modern.api.grpc.v1.Address, com.packt.modern.api.grpc.v1.Address.Builder, com.packt.modern.api.grpc.v1.AddressOrBuilder>(
                getVerifiedAddress(),
                getParentForChildren(),
                isClean());
        verifiedAddress_ = null;
      }
      return verifiedAddressBuilder_;
    }

    private java.lang.Object verifiedEmail_ = "";
    /**
     * <pre>
     * Verified owner’s email address.
     * </pre>
     *
     * <code>string verifiedEmail = 6;</code>
     * @return The verifiedEmail.
     */
    public java.lang.String getVerifiedEmail() {
      java.lang.Object ref = verifiedEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifiedEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Verified owner’s email address.
     * </pre>
     *
     * <code>string verifiedEmail = 6;</code>
     * @return The bytes for verifiedEmail.
     */
    public com.google.protobuf.ByteString
        getVerifiedEmailBytes() {
      java.lang.Object ref = verifiedEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifiedEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Verified owner’s email address.
     * </pre>
     *
     * <code>string verifiedEmail = 6;</code>
     * @param value The verifiedEmail to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifiedEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verified owner’s email address.
     * </pre>
     *
     * <code>string verifiedEmail = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerifiedEmail() {
      
      verifiedEmail_ = getDefaultInstance().getVerifiedEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verified owner’s email address.
     * </pre>
     *
     * <code>string verifiedEmail = 6;</code>
     * @param value The bytes for verifiedEmail to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifiedEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifiedName_ = "";
    /**
     * <pre>
     * Verified owner’s full name.
     * </pre>
     *
     * <code>string verifiedName = 7;</code>
     * @return The verifiedName.
     */
    public java.lang.String getVerifiedName() {
      java.lang.Object ref = verifiedName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifiedName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Verified owner’s full name.
     * </pre>
     *
     * <code>string verifiedName = 7;</code>
     * @return The bytes for verifiedName.
     */
    public com.google.protobuf.ByteString
        getVerifiedNameBytes() {
      java.lang.Object ref = verifiedName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifiedName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Verified owner’s full name.
     * </pre>
     *
     * <code>string verifiedName = 7;</code>
     * @param value The verifiedName to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifiedName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verified owner’s full name.
     * </pre>
     *
     * <code>string verifiedName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerifiedName() {
      
      verifiedName_ = getDefaultInstance().getVerifiedName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verified owner’s full name.
     * </pre>
     *
     * <code>string verifiedName = 7;</code>
     * @param value The bytes for verifiedName to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifiedName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifiedPhone_ = "";
    /**
     * <pre>
     * Verified owner’s phone number
     * </pre>
     *
     * <code>string verifiedPhone = 8;</code>
     * @return The verifiedPhone.
     */
    public java.lang.String getVerifiedPhone() {
      java.lang.Object ref = verifiedPhone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifiedPhone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Verified owner’s phone number
     * </pre>
     *
     * <code>string verifiedPhone = 8;</code>
     * @return The bytes for verifiedPhone.
     */
    public com.google.protobuf.ByteString
        getVerifiedPhoneBytes() {
      java.lang.Object ref = verifiedPhone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifiedPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Verified owner’s phone number
     * </pre>
     *
     * <code>string verifiedPhone = 8;</code>
     * @param value The verifiedPhone to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifiedPhone_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verified owner’s phone number
     * </pre>
     *
     * <code>string verifiedPhone = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerifiedPhone() {
      
      verifiedPhone_ = getDefaultInstance().getVerifiedPhone();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verified owner’s phone number
     * </pre>
     *
     * <code>string verifiedPhone = 8;</code>
     * @param value The bytes for verifiedPhone to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifiedPhone_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.packtpub.v1.Owner)
  }

  // @@protoc_insertion_point(class_scope:com.packtpub.v1.Owner)
  private static final com.packt.modern.api.grpc.v1.Owner DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.packt.modern.api.grpc.v1.Owner();
  }

  public static com.packt.modern.api.grpc.v1.Owner getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Owner>
      PARSER = new com.google.protobuf.AbstractParser<Owner>() {
    @java.lang.Override
    public Owner parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Owner(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Owner> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Owner> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.packt.modern.api.grpc.v1.Owner getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

