// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.packt.modern.api.grpc.v1;

public final class PaymentGatewayService {
  private PaymentGatewayService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_BillingDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_BillingDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_StripeAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_StripeAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_PaymentMethodDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_PaymentMethodDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Refund_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Refund_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_AchCreditTransfer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_AchCreditTransfer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Owner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Owner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Receiver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Receiver_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CreateSourceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CreateSourceReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CreateSourceReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CreateSourceReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_UpdateSourceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_UpdateSourceReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_UpdateSourceReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_UpdateSourceReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_SourceId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_SourceId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_SourceId_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_SourceId_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_AttachOrDetachReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_AttachOrDetachReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_AttachOrDetachReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_AttachOrDetachReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Source_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Source_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CreateChargeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CreateChargeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CreateChargeReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CreateChargeReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_UpdateChargeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_UpdateChargeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_UpdateChargeReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_UpdateChargeReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CaptureChargeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CaptureChargeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CaptureChargeReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CaptureChargeReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_ChargeId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_ChargeId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_ChargeId_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_ChargeId_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CustomerId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CustomerId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_CustomerId_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_CustomerId_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packtpub_v1_Charge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_packtpub_v1_Charge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PaymentGatewayService.proto\022\017com.packt" +
      "pub.v1\032\037google/protobuf/timestamp.proto\"" +
      "\212\001\n\007Address\022\n\n\002id\030\001 \001(\t\022\016\n\006number\030\002 \001(\t\022" +
      "\021\n\tresidency\030\003 \001(\t\022\016\n\006street\030\004 \001(\t\022\014\n\004ci" +
      "ty\030\005 \001(\t\022\r\n\005state\030\006 \001(\t\022\017\n\007country\030\007 \001(\t" +
      "\022\022\n\npostalCode\030\010 \001(\t\"g\n\016BillingDetails\022)" +
      "\n\007address\030\001 \001(\0132\030.com.packtpub.v1.Addres" +
      "s\022\r\n\005email\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\r\n\005phone\030" +
      "\004 \001(\t\"\353\001\n\004Card\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t" +
      "\022)\n\007address\030\003 \001(\0132\030.com.packtpub.v1.Addr" +
      "ess\022\r\n\005brand\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\020\n\010e" +
      "xpMonth\030\006 \001(\r\022\017\n\007expYear\030\007 \001(\r\022\023\n\013finger" +
      "print\030\010 \001(\t\022\017\n\007funding\030\t \001(\t\022\024\n\014installm" +
      "ents\030\n \001(\r\022\r\n\005last4\030\013 \001(\t\022\020\n\010customer\030\014 " +
      "\001(\t\"\033\n\rStripeAccount\022\n\n\002id\030\001 \001(\t\"\200\001\n\024Pay" +
      "mentMethodDetails\022#\n\004card\030\001 \001(\0132\025.com.pa" +
      "cktpub.v1.Card\022\014\n\004type\030\002 \001(\t\0225\n\rstripeAc" +
      "count\030\003 \001(\0132\036.com.packtpub.v1.StripeAcco" +
      "unt\"p\n\006Refund\022\n\n\002id\030\001 \001(\t\022\016\n\006amount\030\002 \001(" +
      "\r\022\013\n\003fee\030\003 \001(\t\022+\n\007created\030\004 \001(\0132\032.google" +
      ".protobuf.Timestamp\022\020\n\010currency\030\005 \001(\t\"{\n" +
      "\021AchCreditTransfer\022\025\n\raccountNumber\030\001 \001(" +
      "\t\022\025\n\rroutingNumber\030\002 \001(\t\022\023\n\013fingerprint\030" +
      "\003 \001(\t\022\020\n\010bankName\030\004 \001(\t\022\021\n\tswiftCode\030\005 \001" +
      "(\t\"\325\001\n\005Owner\022)\n\007address\030\001 \001(\0132\030.com.pack" +
      "tpub.v1.Address\022\r\n\005email\030\002 \001(\t\022\014\n\004name\030\003" +
      " \001(\t\022\r\n\005phone\030\004 \001(\t\0221\n\017verifiedAddress\030\005" +
      " \001(\0132\030.com.packtpub.v1.Address\022\025\n\rverifi" +
      "edEmail\030\006 \001(\t\022\024\n\014verifiedName\030\007 \001(\t\022\025\n\rv" +
      "erifiedPhone\030\010 \001(\t\"\204\003\n\010Receiver\022\017\n\007addre" +
      "ss\030\001 \001(\t\022\025\n\ramountCharged\030\002 \001(\r\022\026\n\016amoun" +
      "tReceived\030\003 \001(\r\022\026\n\016amountReturned\030\004 \001(\r\022" +
      "P\n\026refundAttributesMethod\030\005 \001(\01620.com.pa" +
      "cktpub.v1.Receiver.RefundAttributesMetho" +
      "d\022O\n\026refundAttributesStatus\030\006 \001(\0162/.com." +
      "packtpub.v1.Receiver.RefundAttributeStat" +
      "us\"9\n\026RefundAttributesMethod\022\t\n\005EMAIL\020\000\022" +
      "\n\n\006MANUAL\020\001\022\010\n\004NONE\020\002\"B\n\025RefundAttribute" +
      "Status\022\013\n\007MISSING\020\000\022\r\n\tREQUESTED\020\001\022\r\n\tAV" +
      "AILABLE\020\002\"\263\002\n\017CreateSourceReq\022\014\n\004type\030\001 " +
      "\001(\t\022\016\n\006amount\030\002 \001(\r\022\020\n\010currency\030\003 \001(\t\022%\n" +
      "\005owner\030\004 \001(\0132\026.com.packtpub.v1.Owner\022\033\n\023" +
      "statementDescriptor\030\005 \001(\t\022#\n\004flow\030\006 \001(\0162" +
      "\025.com.packtpub.v1.Flow\022+\n\010receiver\030\007 \001(\013" +
      "2\031.com.packtpub.v1.Receiver\022%\n\005usage\030\010 \001" +
      "(\0162\026.com.packtpub.v1.Usage\0323\n\010Response\022\'" +
      "\n\006source\030\001 \001(\0132\027.com.packtpub.v1.Source\"" +
      "\217\001\n\017UpdateSourceReq\022\020\n\010sourceId\030\001 \001(\t\022\016\n" +
      "\006amount\030\002 \001(\r\022%\n\005owner\030\003 \001(\0132\026.com.packt" +
      "pub.v1.Owner\0323\n\010Response\022\'\n\006source\030\001 \001(\013" +
      "2\027.com.packtpub.v1.Source\"K\n\010SourceId\022\n\n" +
      "\002id\030\001 \001(\t\0323\n\010Response\022\'\n\006source\030\001 \001(\0132\027." +
      "com.packtpub.v1.Source\"n\n\021AttachOrDetach" +
      "Req\022\020\n\010sourceId\030\001 \001(\t\022\022\n\ncustomerId\030\002 \001(" +
      "\t\0323\n\010Response\022\'\n\006source\030\001 \001(\0132\027.com.pack" +
      "tpub.v1.Source\"\250\003\n\006Source\022\n\n\002id\030\001 \001(\t\022\016\n" +
      "\006amount\030\002 \001(\r\022\024\n\014clientSecret\030\003 \001(\t\022\017\n\007c" +
      "reated\030\004 \001(\004\022\020\n\010currency\030\005 \001(\t\022#\n\004flow\030\006" +
      " \001(\0162\025.com.packtpub.v1.Flow\022%\n\005owner\030\007 \001" +
      "(\0132\026.com.packtpub.v1.Owner\022+\n\010receiver\030\010" +
      " \001(\0132\031.com.packtpub.v1.Receiver\022\033\n\023state" +
      "mentDescriptor\030\t \001(\t\022.\n\006status\030\n \001(\0162\036.c" +
      "om.packtpub.v1.Source.Status\022\014\n\004type\030\013 \001" +
      "(\t\022%\n\005usage\030\014 \001(\0162\026.com.packtpub.v1.Usag" +
      "e\"N\n\006Status\022\r\n\tCANCELLED\020\000\022\016\n\nCHARGEABLE" +
      "\020\001\022\014\n\010CONSUMED\020\002\022\n\n\006FAILED\020\003\022\013\n\007PENDING\020" +
      "\004\"\326\001\n\017CreateChargeReq\022\016\n\006amount\030\001 \001(\r\022\020\n" +
      "\010currency\030\002 \001(\t\022\022\n\ncustomerId\030\003 \001(\t\022\023\n\013d" +
      "escription\030\004 \001(\t\022\024\n\014receiptEmail\030\005 \001(\t\022\020" +
      "\n\010sourceId\030\006 \001(\t\022\033\n\023statementDescriptor\030" +
      "\007 \001(\t\0323\n\010Response\022\'\n\006charge\030\001 \001(\0132\027.com." +
      "packtpub.v1.Charge\"\227\001\n\017UpdateChargeReq\022\020" +
      "\n\010chargeId\030\001 \001(\t\022\022\n\ncustomerId\030\002 \001(\t\022\023\n\013" +
      "description\030\003 \001(\t\022\024\n\014receiptEmail\030\004 \001(\t\032" +
      "3\n\010Response\022\'\n\006charge\030\001 \001(\0132\027.com.packtp" +
      "ub.v1.Charge\"\234\001\n\020CaptureChargeReq\022\020\n\010cha" +
      "rgeId\030\001 \001(\t\022\016\n\006amount\030\002 \001(\r\022\024\n\014receiptEm" +
      "ail\030\003 \001(\t\022\033\n\023statementDescriptor\030\004 \001(\t\0323" +
      "\n\010Response\022\'\n\006charge\030\001 \001(\0132\027.com.packtpu" +
      "b.v1.Charge\"K\n\010ChargeId\022\n\n\002id\030\001 \001(\t\0323\n\010R" +
      "esponse\022\'\n\006charge\030\001 \001(\0132\027.com.packtpub.v" +
      "1.Charge\"M\n\nCustomerId\022\n\n\002id\030\001 \001(\t\0323\n\010Re" +
      "sponse\022\'\n\006charge\030\001 \003(\0132\027.com.packtpub.v1" +
      ".Charge\"\371\005\n\006Charge\022\n\n\002id\030\001 \001(\t\022\016\n\006amount" +
      "\030\002 \001(\r\022\026\n\016amountCaptured\030\003 \001(\r\022\026\n\016amount" +
      "Refunded\030\004 \001(\r\022\034\n\024balanceTransactionId\030\005" +
      " \001(\t\0227\n\016billingDetails\030\006 \001(\0132\037.com.packt" +
      "pub.v1.BillingDetails\022%\n\035calculatedState" +
      "mentDescriptor\030\007 \001(\t\022\020\n\010captured\030\010 \001(\010\022\017" +
      "\n\007created\030\t \001(\004\022\020\n\010currency\030\n \001(\t\022\022\n\ncus" +
      "tomerId\030\013 \001(\t\022\023\n\013description\030\014 \001(\t\022\020\n\010di" +
      "sputed\030\r \001(\010\022\023\n\013failureCode\030\016 \001(\r\022\026\n\016fai" +
      "lureMessage\030\017 \001(\t\022\021\n\tinvoiceId\030\020 \001(\t\022\017\n\007" +
      "orderId\030\021 \001(\t\022\014\n\004paid\030\022 \001(\010\022\027\n\017paymentMe" +
      "thodId\030\023 \001(\t\022C\n\024paymentMethodDetails\030\024 \001" +
      "(\0132%.com.packtpub.v1.PaymentMethodDetail" +
      "s\022\024\n\014receiptEmail\030\025 \001(\t\022\025\n\rreceiptNumber" +
      "\030\026 \001(\t\022\020\n\010refunded\030\027 \001(\010\022(\n\007refunds\030\030 \003(" +
      "\0132\027.com.packtpub.v1.Refund\022\033\n\023statementD" +
      "escriptor\030\031 \001(\t\022.\n\006status\030\032 \001(\0162\036.com.pa" +
      "cktpub.v1.Charge.Status\022\020\n\010sourceId\030\033 \001(" +
      "\t\"0\n\006Status\022\r\n\tSUCCEEDED\020\000\022\013\n\007PENDING\020\001\022" +
      "\n\n\006FAILED\020\002*B\n\004Flow\022\014\n\010REDIRECT\020\000\022\014\n\010REC" +
      "EIVER\020\001\022\024\n\020CODEVERIFICATION\020\002\022\010\n\004NONE\020\003*" +
      "$\n\005Usage\022\014\n\010REUSABLE\020\000\022\r\n\tSINGLEUSE\020\0012\264\003" +
      "\n\rChargeService\022U\n\006Create\022 .com.packtpub" +
      ".v1.CreateChargeReq\032).com.packtpub.v1.Cr" +
      "eateChargeReq.Response\022I\n\010Retrieve\022\031.com" +
      ".packtpub.v1.ChargeId\032\".com.packtpub.v1." +
      "ChargeId.Response\022U\n\006Update\022 .com.packtp" +
      "ub.v1.UpdateChargeReq\032).com.packtpub.v1." +
      "UpdateChargeReq.Response\022X\n\007Capture\022!.co" +
      "m.packtpub.v1.CaptureChargeReq\032*.com.pac" +
      "ktpub.v1.CaptureChargeReq.Response\022P\n\013Re" +
      "trieveAll\022\033.com.packtpub.v1.CustomerId\032$" +
      ".com.packtpub.v1.CustomerId.Response2\276\003\n" +
      "\rSourceService\022U\n\006Create\022 .com.packtpub." +
      "v1.CreateSourceReq\032).com.packtpub.v1.Cre" +
      "ateSourceReq.Response\022I\n\010Retrieve\022\031.com." +
      "packtpub.v1.SourceId\032\".com.packtpub.v1.S" +
      "ourceId.Response\022U\n\006Update\022 .com.packtpu" +
      "b.v1.UpdateSourceReq\032).com.packtpub.v1.U" +
      "pdateSourceReq.Response\022Y\n\006Attach\022\".com." +
      "packtpub.v1.AttachOrDetachReq\032+.com.pack" +
      "tpub.v1.AttachOrDetachReq.Response\022Y\n\006De" +
      "tach\022\".com.packtpub.v1.AttachOrDetachReq" +
      "\032+.com.packtpub.v1.AttachOrDetachReq.Res" +
      "ponseB \n\034com.packt.modern.api.grpc.v1P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_packtpub_v1_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_packtpub_v1_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Address_descriptor,
        new java.lang.String[] { "Id", "Number", "Residency", "Street", "City", "State", "Country", "PostalCode", });
    internal_static_com_packtpub_v1_BillingDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_packtpub_v1_BillingDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_BillingDetails_descriptor,
        new java.lang.String[] { "Address", "Email", "Name", "Phone", });
    internal_static_com_packtpub_v1_Card_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_packtpub_v1_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Card_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", "Brand", "Country", "ExpMonth", "ExpYear", "Fingerprint", "Funding", "Installments", "Last4", "Customer", });
    internal_static_com_packtpub_v1_StripeAccount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_packtpub_v1_StripeAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_StripeAccount_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_packtpub_v1_PaymentMethodDetails_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_packtpub_v1_PaymentMethodDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_PaymentMethodDetails_descriptor,
        new java.lang.String[] { "Card", "Type", "StripeAccount", });
    internal_static_com_packtpub_v1_Refund_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_packtpub_v1_Refund_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Refund_descriptor,
        new java.lang.String[] { "Id", "Amount", "Fee", "Created", "Currency", });
    internal_static_com_packtpub_v1_AchCreditTransfer_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_packtpub_v1_AchCreditTransfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_AchCreditTransfer_descriptor,
        new java.lang.String[] { "AccountNumber", "RoutingNumber", "Fingerprint", "BankName", "SwiftCode", });
    internal_static_com_packtpub_v1_Owner_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_packtpub_v1_Owner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Owner_descriptor,
        new java.lang.String[] { "Address", "Email", "Name", "Phone", "VerifiedAddress", "VerifiedEmail", "VerifiedName", "VerifiedPhone", });
    internal_static_com_packtpub_v1_Receiver_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_packtpub_v1_Receiver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Receiver_descriptor,
        new java.lang.String[] { "Address", "AmountCharged", "AmountReceived", "AmountReturned", "RefundAttributesMethod", "RefundAttributesStatus", });
    internal_static_com_packtpub_v1_CreateSourceReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_packtpub_v1_CreateSourceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CreateSourceReq_descriptor,
        new java.lang.String[] { "Type", "Amount", "Currency", "Owner", "StatementDescriptor", "Flow", "Receiver", "Usage", });
    internal_static_com_packtpub_v1_CreateSourceReq_Response_descriptor =
      internal_static_com_packtpub_v1_CreateSourceReq_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_CreateSourceReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CreateSourceReq_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_packtpub_v1_UpdateSourceReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_packtpub_v1_UpdateSourceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_UpdateSourceReq_descriptor,
        new java.lang.String[] { "SourceId", "Amount", "Owner", });
    internal_static_com_packtpub_v1_UpdateSourceReq_Response_descriptor =
      internal_static_com_packtpub_v1_UpdateSourceReq_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_UpdateSourceReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_UpdateSourceReq_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_packtpub_v1_SourceId_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_packtpub_v1_SourceId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_SourceId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_packtpub_v1_SourceId_Response_descriptor =
      internal_static_com_packtpub_v1_SourceId_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_SourceId_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_SourceId_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_packtpub_v1_AttachOrDetachReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_packtpub_v1_AttachOrDetachReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_AttachOrDetachReq_descriptor,
        new java.lang.String[] { "SourceId", "CustomerId", });
    internal_static_com_packtpub_v1_AttachOrDetachReq_Response_descriptor =
      internal_static_com_packtpub_v1_AttachOrDetachReq_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_AttachOrDetachReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_AttachOrDetachReq_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_packtpub_v1_Source_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_packtpub_v1_Source_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Source_descriptor,
        new java.lang.String[] { "Id", "Amount", "ClientSecret", "Created", "Currency", "Flow", "Owner", "Receiver", "StatementDescriptor", "Status", "Type", "Usage", });
    internal_static_com_packtpub_v1_CreateChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_packtpub_v1_CreateChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CreateChargeReq_descriptor,
        new java.lang.String[] { "Amount", "Currency", "CustomerId", "Description", "ReceiptEmail", "SourceId", "StatementDescriptor", });
    internal_static_com_packtpub_v1_CreateChargeReq_Response_descriptor =
      internal_static_com_packtpub_v1_CreateChargeReq_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_CreateChargeReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CreateChargeReq_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_packtpub_v1_UpdateChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_packtpub_v1_UpdateChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_UpdateChargeReq_descriptor,
        new java.lang.String[] { "ChargeId", "CustomerId", "Description", "ReceiptEmail", });
    internal_static_com_packtpub_v1_UpdateChargeReq_Response_descriptor =
      internal_static_com_packtpub_v1_UpdateChargeReq_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_UpdateChargeReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_UpdateChargeReq_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_packtpub_v1_CaptureChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_packtpub_v1_CaptureChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CaptureChargeReq_descriptor,
        new java.lang.String[] { "ChargeId", "Amount", "ReceiptEmail", "StatementDescriptor", });
    internal_static_com_packtpub_v1_CaptureChargeReq_Response_descriptor =
      internal_static_com_packtpub_v1_CaptureChargeReq_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_CaptureChargeReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CaptureChargeReq_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_packtpub_v1_ChargeId_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_packtpub_v1_ChargeId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_ChargeId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_packtpub_v1_ChargeId_Response_descriptor =
      internal_static_com_packtpub_v1_ChargeId_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_ChargeId_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_ChargeId_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_packtpub_v1_CustomerId_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_packtpub_v1_CustomerId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CustomerId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_packtpub_v1_CustomerId_Response_descriptor =
      internal_static_com_packtpub_v1_CustomerId_descriptor.getNestedTypes().get(0);
    internal_static_com_packtpub_v1_CustomerId_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_CustomerId_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_packtpub_v1_Charge_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_packtpub_v1_Charge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_packtpub_v1_Charge_descriptor,
        new java.lang.String[] { "Id", "Amount", "AmountCaptured", "AmountRefunded", "BalanceTransactionId", "BillingDetails", "CalculatedStatementDescriptor", "Captured", "Created", "Currency", "CustomerId", "Description", "Disputed", "FailureCode", "FailureMessage", "InvoiceId", "OrderId", "Paid", "PaymentMethodId", "PaymentMethodDetails", "ReceiptEmail", "ReceiptNumber", "Refunded", "Refunds", "StatementDescriptor", "Status", "SourceId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
